"""
OAuth 2.0 login providers — for authenticating INTO this app, not for
publishing. See oauth_platforms.py for the publish-side connectors.
"""
import base64
import hashlib
import os
import secrets
import requests

GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")
LINKEDIN_CLIENT_ID = os.environ.get("LINKEDIN_CLIENT_ID")
LINKEDIN_CLIENT_SECRET = os.environ.get("LINKEDIN_CLIENT_SECRET")
META_APP_ID = os.environ.get("META_APP_ID")
META_APP_SECRET = os.environ.get("META_APP_SECRET")
X_CLIENT_ID = os.environ.get("X_CLIENT_ID")
X_CLIENT_SECRET = os.environ.get("X_CLIENT_SECRET")
BACKEND_BASE_URL = os.environ.get("BACKEND_BASE_URL", "http://localhost:8000")


def _redirect_uri(provider: str) -> str:
    return f"{BACKEND_BASE_URL}/auth/{provider}/callback"


# ---------- Google ----------

def google_authorize_url(state: str, **_) -> str:
    return (
        "https://accounts.google.com/o/oauth2/v2/auth"
        f"?response_type=code&client_id={GOOGLE_CLIENT_ID}&redirect_uri={_redirect_uri('google')}"
        f"&scope=openid%20email%20profile&state={state}"
    )


def google_finish(code: str, **_) -> dict:
    resp = requests.post(
        "https://oauth2.googleapis.com/token",
        data={"code": code, "client_id": GOOGLE_CLIENT_ID, "client_secret": GOOGLE_CLIENT_SECRET,
              "redirect_uri": _redirect_uri("google"), "grant_type": "authorization_code"},
        timeout=15,
    )
    resp.raise_for_status()
    access_token = resp.json()["access_token"]

    info = requests.get(
        "https://openidconnect.googleapis.com/v1/userinfo",
        headers={"Authorization": f"Bearer {access_token}"},
        timeout=15,
    )
    info.raise_for_status()
    data = info.json()
    return {"provider_user_id": data["sub"], "email": data.get("email"), "name": data.get("name")}


# ---------- LinkedIn (login scope — separate from the publish-connector scope) ----------

def linkedin_authorize_url(state: str, **_) -> str:
    return (
        "https://www.linkedin.com/oauth/v2/authorization"
        f"?response_type=code&client_id={LINKEDIN_CLIENT_ID}&redirect_uri={_redirect_uri('linkedin')}"
        f"&scope=openid%20profile%20email&state={state}"
    )


def linkedin_finish(code: str, **_) -> dict:
    resp = requests.post(
        "https://www.linkedin.com/oauth/v2/accessToken",
        data={"grant_type": "authorization_code", "code": code, "redirect_uri": _redirect_uri("linkedin"),
              "client_id": LINKEDIN_CLIENT_ID, "client_secret": LINKEDIN_CLIENT_SECRET},
        timeout=15,
    )
    resp.raise_for_status()
    access_token = resp.json()["access_token"]

    info = requests.get(
        "https://api.linkedin.com/v2/userinfo",
        headers={"Authorization": f"Bearer {access_token}"},
        timeout=15,
    )
    info.raise_for_status()
    data = info.json()
    return {"provider_user_id": data["sub"], "email": data.get("email"), "name": data.get("name")}


# ---------- Facebook (login) ----------

def facebook_authorize_url(state: str, **_) -> str:
    return (
        "https://www.facebook.com/v21.0/dialog/oauth"
        f"?client_id={META_APP_ID}&redirect_uri={_redirect_uri('facebook')}"
        f"&scope=public_profile,email&state={state}"
    )


def facebook_finish(code: str, **_) -> dict:
    resp = requests.get(
        "https://graph.facebook.com/v21.0/oauth/access_token",
        params={"client_id": META_APP_ID, "redirect_uri": _redirect_uri("facebook"),
                "client_secret": META_APP_SECRET, "code": code},
        timeout=15,
    )
    resp.raise_for_status()
    access_token = resp.json()["access_token"]

    info = requests.get(
        "https://graph.facebook.com/me",
        params={"fields": "id,name,email", "access_token": access_token},
        timeout=15,
    )
    info.raise_for_status()
    data = info.json()
    return {"provider_user_id": data["id"], "email": data.get("email"), "name": data.get("name")}


# ---------- X (requires PKCE) ----------

def _pkce_pair() -> tuple[str, str]:
    verifier = secrets.token_urlsafe(64)[:128]
    challenge = base64.urlsafe_b64encode(hashlib.sha256(verifier.encode()).digest()).decode().rstrip("=")
    return verifier, challenge


def x_authorize_url(state: str, code_verifier: str | None = None, **_) -> str:
    # code_verifier is generated by the caller and passed back in on finish()
    _, challenge = code_verifier, _pkce_pair()[1] if code_verifier is None else None
    raise RuntimeError("x_authorize_url must be called via x_start(), not directly")


def x_start(state: str) -> tuple[str, str]:
    """Returns (authorize_url, code_verifier) — the verifier must be stored
    against this state, since X needs it back at token-exchange time."""
    verifier, challenge = _pkce_pair()
    url = (
        "https://twitter.com/i/oauth2/authorize"
        f"?response_type=code&client_id={X_CLIENT_ID}&redirect_uri={_redirect_uri('x')}"
        f"&scope=users.read%20tweet.read&state={state}"
        f"&code_challenge={challenge}&code_challenge_method=S256"
    )
    return url, verifier


def x_finish(code: str, code_verifier: str | None = None, **_) -> dict:
    resp = requests.post(
        "https://api.twitter.com/2/oauth2/token",
        data={"code": code, "grant_type": "authorization_code", "client_id": X_CLIENT_ID,
              "redirect_uri": _redirect_uri("x"), "code_verifier": code_verifier},
        auth=(X_CLIENT_ID, X_CLIENT_SECRET),
        timeout=15,
    )
    resp.raise_for_status()
    access_token = resp.json()["access_token"]

    info = requests.get(
        "https://api.twitter.com/2/users/me",
        headers={"Authorization": f"Bearer {access_token}"},
        timeout=15,
    )
    info.raise_for_status()
    data = info.json()["data"]
    return {"provider_user_id": data["id"], "email": None, "name": data.get("name") or data.get("username")}


LOGIN_PROVIDERS = {
    "google": {"authorize_url": google_authorize_url, "finish": google_finish},
    "linkedin": {"authorize_url": linkedin_authorize_url, "finish": linkedin_finish},
    "facebook": {"authorize_url": facebook_authorize_url, "finish": facebook_finish},
}