// Full emoji dataset grouped by category, with search keywords per emoji.
// Used by Form.jsx's emoji picker (search + category tabs + frequently used).

export const EMOJI_CATEGORY_META = [
    { key: "frequent", label: "Frequently used", icon: "🕘" },
    { key: "smileys", label: "Smileys & People", icon: "😀" },
    { key: "animals", label: "Animals & Nature", icon: "🐶" },
    { key: "food", label: "Food & Drink", icon: "🍔" },
    { key: "activities", label: "Activities", icon: "⚽" },
    { key: "travel", label: "Travel & Places", icon: "🚗" },
    { key: "objects", label: "Objects", icon: "💡" },
    { key: "symbols", label: "Symbols", icon: "💠" },
    { key: "flags", label: "Flags", icon: "🏳️" },
  ];
  
  const RAW = {
    smileys: [
      ["😀", "grinning face happy smile"], ["😃", "grinning smile happy joy"],
      ["😄", "smile happy laugh joy"], ["😁", "grin beam smile"],
      ["😆", "laugh haha smile"], ["😅", "sweat smile laugh relief"],
      ["🤣", "rofl laugh floor"], ["😂", "joy laugh cry tears"],
      ["🙂", "slight smile"], ["🙃", "upside down smile"],
      ["😉", "wink"], ["😊", "smile blush happy"],
      ["😇", "innocent halo angel"], ["🥰", "love hearts smile"],
      ["😍", "heart eyes love"], ["🤩", "star struck excited"],
      ["😘", "kiss love"], ["😗", "kiss"], ["😚", "kiss closed eyes"],
      ["😙", "kiss smile"], ["😋", "yum tongue tasty"],
      ["😛", "tongue playful"], ["😜", "wink tongue crazy"],
      ["🤪", "zany crazy silly"], ["😝", "tongue squint"],
      ["🤑", "money mouth greedy"], ["🤗", "hug"],
      ["🤭", "giggle oops hand mouth"], ["🤫", "shush quiet"],
      ["🤔", "thinking hmm"], ["🤐", "zipper mouth quiet"],
      ["🤨", "raised eyebrow skeptical"], ["😐", "neutral"],
      ["😑", "expressionless blank"], ["😶", "no mouth silent"],
      ["😏", "smirk"], ["😒", "unamused annoyed"],
      ["🙄", "eye roll annoyed"], ["😬", "grimace awkward"],
      ["🤥", "lying pinocchio nose"], ["😌", "relieved content"],
      ["😔", "pensive sad"], ["😪", "sleepy tired"],
      ["🤤", "drool"], ["😴", "sleep zzz"],
      ["😷", "mask sick"], ["🤒", "thermometer sick fever"],
      ["🤕", "bandage hurt injured"], ["🤢", "nauseated sick"],
      ["🤮", "vomit sick"], ["🤧", "sneeze sick"],
      ["🥵", "hot sweat heat"], ["🥶", "cold freezing"],
      ["🥴", "woozy dizzy"], ["😵", "dizzy knocked out"],
      ["🤯", "mind blown shocked"], ["🤠", "cowboy hat"],
      ["🥳", "party celebrate"], ["🥸", "disguise glasses"],
      ["😎", "sunglasses cool"], ["🤓", "nerd glasses"],
      ["🧐", "monocle curious"], ["😕", "confused"],
      ["😟", "worried"], ["🙁", "frown sad"],
      ["☹️", "frown sad"], ["😮", "open mouth surprised"],
      ["😯", "hushed surprised"], ["😲", "astonished shocked"],
      ["😳", "flushed embarrassed"], ["🥺", "pleading puppy eyes"],
      ["😦", "frown open mouth"], ["😧", "anguished"],
      ["😨", "fearful scared"], ["😰", "anxious sweat"],
      ["😥", "sad relieved"], ["😢", "cry sad tear"],
      ["😭", "sob cry loud"], ["😱", "scream fear"],
      ["😖", "confounded"], ["😣", "persevere struggle"],
      ["😞", "disappointed"], ["😓", "downcast sweat"],
      ["😩", "weary tired"], ["😫", "tired exhausted"],
      ["🥱", "yawn tired"], ["😤", "triumph huff"],
      ["😡", "rage angry mad"], ["😠", "angry mad"],
      ["🤬", "cursing swearing angry"], ["😈", "smiling devil"],
      ["👿", "angry devil"], ["💀", "skull dead"],
      ["☠️", "skull crossbones danger"], ["💩", "poop"],
      ["🤡", "clown"], ["👹", "ogre monster"],
      ["👺", "goblin monster"], ["👻", "ghost"],
      ["👽", "alien"], ["👾", "alien monster space"],
      ["🤖", "robot"], ["😺", "cat happy"],
      ["😸", "cat grin"], ["😹", "cat joy tears"],
      ["😻", "cat heart eyes love"], ["😼", "cat smirk"],
      ["😽", "cat kiss"], ["🙀", "cat scream"],
      ["😿", "cat cry sad"], ["😾", "cat pouting"],
      ["🙈", "see no evil monkey"], ["🙉", "hear no evil monkey"],
      ["🙊", "speak no evil monkey"], ["💋", "kiss lips"],
      ["💌", "love letter"], ["💘", "cupid arrow heart"],
      ["💝", "gift heart"], ["💖", "sparkle heart"],
      ["💗", "growing heart"], ["💓", "beating heart"],
      ["💞", "revolving hearts"], ["💕", "two hearts"],
      ["💟", "heart decoration"], ["❣️", "heart exclamation"],
      ["💔", "broken heart"], ["❤️", "red heart love"],
      ["🧡", "orange heart"], ["💛", "yellow heart"],
      ["💚", "green heart"], ["💙", "blue heart"],
      ["💜", "purple heart"], ["🤎", "brown heart"],
      ["🖤", "black heart"], ["🤍", "white heart"],
      ["💯", "hundred perfect score"], ["💢", "anger symbol"],
      ["💥", "collision boom"], ["💫", "dizzy stars"],
      ["💦", "sweat drops splash"], ["💨", "dash wind fast"],
      ["🕳️", "hole"], ["💣", "bomb explode"],
      ["💬", "speech bubble"], ["👋", "wave hand hello bye"],
      ["🤚", "raised back hand"], ["🖐️", "hand fingers spread"],
      ["✋", "raised hand stop"], ["🖖", "vulcan salute"],
      ["👌", "ok hand"], ["🤌", "pinched fingers"],
      ["🤏", "pinch small"], ["✌️", "peace victory"],
      ["🤞", "fingers crossed luck"], ["🤟", "love you gesture"],
      ["🤘", "rock on"], ["🤙", "call me shaka"],
      ["👈", "point left"], ["👉", "point right"],
      ["👆", "point up"], ["🖕", "middle finger"],
      ["👇", "point down"], ["☝️", "point up one"],
      ["👍", "thumbs up like"], ["👎", "thumbs down dislike"],
      ["✊", "raised fist"], ["👊", "punch fist bump"],
      ["🤛", "left fist bump"], ["🤜", "right fist bump"],
      ["👏", "clap applause"], ["🙌", "raise hands celebrate"],
      ["👐", "open hands"], ["🤲", "palms up"],
      ["🤝", "handshake deal"], ["🙏", "pray thanks please"],
      ["✍️", "writing hand"], ["💅", "nail polish"],
      ["🤳", "selfie"], ["💪", "muscle flex strong"],
      ["🦾", "mechanical arm"], ["🦵", "leg"],
      ["👂", "ear"], ["👃", "nose"],
      ["🧠", "brain"], ["👀", "eyes look"],
      ["👁️", "eye"], ["👅", "tongue"],
      ["👄", "mouth lips"], ["👶", "baby"],
      ["🧒", "child kid"], ["👦", "boy"],
      ["👧", "girl"], ["🧑", "person adult"],
      ["👱", "blond person"], ["👨", "man"],
      ["🧔", "man beard"], ["👩", "woman"],
      ["🧓", "older person"], ["👴", "old man"],
      ["👵", "old woman"], ["🙍", "frowning person"],
      ["🙎", "pouting person"], ["🙅", "no gesture person"],
      ["🙆", "ok gesture person"], ["💁", "tipping hand person"],
      ["🙋", "raising hand person"], ["🧏", "deaf person"],
      ["🙇", "bowing person"], ["🤦", "facepalm"],
      ["🤷", "shrug"], ["👮", "police officer"],
      ["🕵️", "detective spy"], ["💂", "guard"],
      ["👷", "construction worker"], ["🤴", "prince"],
      ["👸", "princess"], ["👳", "turban person"],
      ["👲", "cap person"], ["🧕", "headscarf woman"],
      ["🤵", "tuxedo person groom"], ["👰", "veil bride"],
      ["🤰", "pregnant"], ["🤱", "breastfeeding"],
      ["👼", "baby angel"], ["🎅", "santa claus"],
      ["🤶", "mrs claus"], ["🦸", "superhero"],
      ["🦹", "supervillain"], ["🧙", "mage wizard"],
      ["🧚", "fairy"], ["🧛", "vampire"],
      ["🧜", "mermaid"], ["🧝", "elf"],
      ["🧞", "genie"], ["🧟", "zombie"],
      ["💆", "massage relax"], ["💇", "haircut"],
      ["🚶", "walking person"], ["🧍", "standing person"],
      ["🧎", "kneeling person"], ["🏃", "running person"],
      ["💃", "dancing woman"], ["🕺", "dancing man"],
      ["👯", "bunny ears people"], ["🧖", "steamy sauna person"],
      ["🧗", "climbing person"], ["🤺", "fencing"],
      ["🏇", "horse racing"], ["⛷️", "skiing"],
      ["🏂", "snowboarding"], ["🏌️", "golfing"],
      ["🏄", "surfing"], ["🚣", "rowing boat"],
      ["🏊", "swimming"], ["⛹️", "bouncing ball person"],
      ["🏋️", "weight lifting"], ["🚴", "cycling"],
      ["🚵", "mountain biking"], ["🤸", "cartwheel"],
      ["🤼", "wrestling"], ["🤽", "water polo"],
      ["🤾", "handball"], ["🤹", "juggling"],
      ["🧘", "meditation yoga"], ["🛀", "bath"],
      ["🛌", "in bed sleep"], ["👭", "women holding hands"],
      ["👫", "couple holding hands"], ["👬", "men holding hands"],
      ["💏", "kiss couple"], ["💑", "couple with heart"],
      ["👪", "family"], ["🗣️", "speaking head"],
      ["👤", "bust silhouette"], ["👥", "busts silhouette"],
      ["🫂", "hugging people"],
      ["🤍", "white heart"], ["🫶", "heart hands"], ["🫰", "finger heart"],
      ["🫡", "salute"], ["🫠", "melting face"], ["🥹", "holding back tears"],
      ["🫤", "diagonal mouth"], ["😵‍💫", "spiral dizzy"], ["😮‍💨", "exhale relieved"],
      ["😶‍🌫️", "face in clouds"], ["❤️‍🔥", "heart on fire"], ["❤️‍🩹", "mending heart"],
      ["🫥", "dotted line face invisible"], ["🫨", "shaking face"], ["🥲", "smiling tear"],
    ],
    animals: [
      ["🐶", "dog puppy"], ["🐱", "cat kitten"], ["🐭", "mouse"],
      ["🐹", "hamster"], ["🐰", "rabbit bunny"], ["🦊", "fox"],
      ["🐻", "bear"], ["🐼", "panda"], ["🐻‍❄️", "polar bear"],
      ["🐨", "koala"], ["🐯", "tiger"], ["🦁", "lion"],
      ["🐮", "cow"], ["🐷", "pig"], ["🐽", "pig nose"],
      ["🐸", "frog"], ["🐵", "monkey"], ["🙈", "see no evil"],
      ["🙉", "hear no evil"], ["🙊", "speak no evil"],
      ["🐒", "monkey"], ["🐔", "chicken"], ["🐧", "penguin"],
      ["🐦", "bird"], ["🐤", "chick baby bird"], ["🐣", "hatching chick"],
      ["🐥", "front facing chick"], ["🦆", "duck"], ["🦅", "eagle"],
      ["🦉", "owl"], ["🦇", "bat"], ["🐺", "wolf"],
      ["🐗", "boar"], ["🐴", "horse"], ["🦄", "unicorn"],
      ["🐝", "bee"], ["🪱", "worm"], ["🐛", "caterpillar"],
      ["🦋", "butterfly"], ["🐌", "snail"], ["🐞", "ladybug"],
      ["🐜", "ant"], ["🪰", "fly"], ["🪲", "beetle"],
      ["🪳", "cockroach"], ["🦟", "mosquito"], ["🦗", "cricket"],
      ["🕷️", "spider"], ["🕸️", "spider web"], ["🦂", "scorpion"],
      ["🐢", "turtle"], ["🐍", "snake"], ["🦎", "lizard"],
      ["🦖", "t-rex dinosaur"], ["🦕", "sauropod dinosaur"],
      ["🐙", "octopus"], ["🦑", "squid"], ["🦐", "shrimp"],
      ["🦞", "lobster"], ["🦀", "crab"], ["🐡", "blowfish"],
      ["🐠", "tropical fish"], ["🐟", "fish"], ["🐬", "dolphin"],
      ["🐳", "whale"], ["🐋", "whale"], ["🦈", "shark"],
      ["🐊", "crocodile"], ["🐅", "tiger"], ["🐆", "leopard"],
      ["🦓", "zebra"], ["🦍", "gorilla"], ["🦧", "orangutan"],
      ["🦣", "mammoth"], ["🐘", "elephant"], ["🦛", "hippo"],
      ["🦏", "rhino"], ["🐪", "camel"], ["🐫", "two hump camel"],
      ["🦒", "giraffe"], ["🦘", "kangaroo"], ["🦬", "bison"],
      ["🐃", "water buffalo"], ["🐂", "ox"], ["🐄", "cow"],
      ["🐎", "horse racing"], ["🐖", "pig"], ["🐏", "ram"],
      ["🐑", "ewe sheep"], ["🦙", "llama"], ["🐐", "goat"],
      ["🦌", "deer"], ["🐕", "dog"], ["🐩", "poodle"],
      ["🦮", "guide dog"], ["🐕‍🦺", "service dog"], ["🐈", "cat"],
      ["🐈‍⬛", "black cat"], ["🪶", "feather"], ["🐓", "rooster"],
      ["🦃", "turkey"], ["🦤", "dodo"], ["🦚", "peacock"],
      ["🦜", "parrot"], ["🦢", "swan"], ["🦩", "flamingo"],
      ["🕊️", "dove peace"], ["🐇", "rabbit"], ["🦝", "raccoon"],
      ["🦨", "skunk"], ["🦡", "badger"], ["🦫", "beaver"],
      ["🦦", "otter"], ["🦥", "sloth"], ["🐁", "mouse"],
      ["🐀", "rat"], ["🐿️", "squirrel/chipmunk"], ["🦔", "hedgehog"],
      ["🐾", "paw prints"], ["🐉", "dragon"], ["🐲", "dragon face"],
      ["🌵", "cactus"], ["🎄", "christmas tree"], ["🌲", "evergreen tree"],
      ["🌳", "deciduous tree"], ["🌴", "palm tree"], ["🪵", "wood log"],
      ["🌱", "seedling"], ["🌿", "herb"], ["☘️", "shamrock"],
      ["🍀", "four leaf clover luck"], ["🎍", "pine decoration"],
      ["🪴", "potted plant"], ["🎋", "tanabata tree"], ["🍃", "leaves wind"],
      ["🍂", "fallen leaf autumn"], ["🍁", "maple leaf"], ["🍄", "mushroom"],
      ["🐚", "shell"], ["🪨", "rock"], ["🌾", "sheaf rice"],
      ["💐", "bouquet flowers"], ["🌷", "tulip"], ["🌹", "rose"],
      ["🥀", "wilted rose"], ["🪷", "lotus"], ["🌺", "hibiscus"],
      ["🌸", "cherry blossom"], ["🌼", "blossom daisy"], ["🌻", "sunflower"],
      ["☀️", "sun"], ["🌤️", "sun cloud"], ["⛅", "cloud sun"],
      ["🌦️", "sun rain cloud"], ["🌧️", "rain cloud"], ["⛈️", "thunderstorm"],
      ["🌩️", "lightning cloud"], ["🌨️", "snow cloud"], ["❄️", "snowflake"],
      ["☃️", "snowman"], ["⛄", "snowman"], ["🌬️", "wind"],
      ["💨", "dash wind"], ["🌪️", "tornado"], ["🌫️", "fog"],
      ["🌈", "rainbow"], ["☂️", "umbrella"], ["☔", "umbrella rain"],
      ["⚡", "lightning bolt"], ["❄️", "snow"], ["🔥", "fire"],
      ["💧", "droplet water"], ["🌊", "wave ocean water"],
      ["🌙", "crescent moon"], ["🌛", "moon face"], ["🌜", "moon face"],
      ["🌞", "sun face"], ["🌝", "full moon face"], ["🌚", "new moon face"],
      ["⭐", "star"], ["🌟", "glowing star"], ["✨", "sparkles"],
      ["⚡", "high voltage"], ["☄️", "comet"], ["💫", "dizzy"],
      ["🌍", "earth globe"], ["🌎", "earth globe americas"], ["🌏", "earth globe asia"],
    ],
    food: [
      ["🍏", "green apple"], ["🍎", "red apple"], ["🍐", "pear"],
      ["🍊", "orange tangerine"], ["🍋", "lemon"], ["🍌", "banana"],
      ["🍉", "watermelon"], ["🍇", "grapes"], ["🍓", "strawberry"],
      ["🫐", "blueberries"], ["🍈", "melon"], ["🍒", "cherries"],
      ["🍑", "peach"], ["🥭", "mango"], ["🍍", "pineapple"],
      ["🥥", "coconut"], ["🥝", "kiwi"], ["🍅", "tomato"],
      ["🍆", "eggplant"], ["🥑", "avocado"], ["🥦", "broccoli"],
      ["🥬", "leafy green"], ["🥒", "cucumber"], ["🌶️", "hot pepper spicy"],
      ["🫑", "bell pepper"], ["🌽", "corn"], ["🥕", "carrot"],
      ["🫒", "olive"], ["🧄", "garlic"], ["🧅", "onion"],
      ["🥔", "potato"], ["🍠", "sweet potato"], ["🥐", "croissant"],
      ["🥯", "bagel"], ["🍞", "bread"], ["🥖", "baguette"],
      ["🥨", "pretzel"], ["🧀", "cheese"], ["🥚", "egg"],
      ["🍳", "cooking fried egg"], ["🧈", "butter"], ["🥞", "pancakes"],
      ["🧇", "waffle"], ["🥓", "bacon"], ["🥩", "meat steak"],
      ["🍗", "poultry leg chicken"], ["🍖", "meat bone"], ["🌭", "hot dog"],
      ["🍔", "burger hamburger"], ["🍟", "fries"], ["🍕", "pizza"],
      ["🫓", "flatbread"], ["🥪", "sandwich"], ["🥙", "stuffed flatbread"],
      ["🧆", "falafel"], ["🌮", "taco"], ["🌯", "burrito"],
      ["🫔", "tamale"], ["🥗", "salad"], ["🥘", "paella pan"],
      ["🫕", "fondue"], ["🥫", "canned food"], ["🍝", "spaghetti pasta"],
      ["🍜", "ramen noodle soup"], ["🍲", "stew pot"], ["🍛", "curry rice"],
      ["🍣", "sushi"], ["🍱", "bento box"], ["🥟", "dumpling"],
      ["🦪", "oyster"], ["🍤", "fried shrimp tempura"], ["🍙", "rice ball"],
      ["🍚", "rice"], ["🍘", "rice cracker"], ["🍥", "fish cake"],
      ["🥠", "fortune cookie"], ["🥮", "moon cake"], ["🍢", "oden skewer"],
      ["🍡", "dango"], ["🍧", "shaved ice"], ["🍨", "ice cream"],
      ["🍦", "soft serve ice cream"], ["🥧", "pie"], ["🧁", "cupcake"],
      ["🍰", "cake slice"], ["🎂", "birthday cake"], ["🍮", "custard flan"],
      ["🍭", "lollipop"], ["🍬", "candy"], ["🍫", "chocolate"],
      ["🍿", "popcorn"], ["🍩", "donut"], ["🍪", "cookie"],
      ["🌰", "chestnut"], ["🥜", "peanuts"], ["🍯", "honey"],
      ["🥛", "milk glass"], ["🍼", "baby bottle"], ["☕", "coffee"],
      ["🫖", "teapot"], ["🍵", "tea"], ["🧃", "juice box"],
      ["🥤", "cup with straw soda"], ["🧋", "bubble tea"], ["🍶", "sake"],
      ["🍺", "beer"], ["🍻", "beers cheers"], ["🥂", "champagne glasses"],
      ["🍷", "wine glass"], ["🥃", "whiskey glass"], ["🍸", "cocktail"],
      ["🍹", "tropical drink"], ["🧉", "mate drink"], ["🍾", "champagne bottle"],
      ["🧊", "ice cube"], ["🥢", "chopsticks"], ["🍽️", "fork knife plate"],
      ["🍴", "fork and knife"], ["🥄", "spoon"], ["🔪", "knife"],
      ["🫙", "jar"], ["🏺", "amphora"],
    ],
    activities: [
      ["⚽", "soccer football"], ["🏀", "basketball"], ["🏈", "american football"],
      ["⚾", "baseball"], ["🥎", "softball"], ["🎾", "tennis"],
      ["🏐", "volleyball"], ["🏉", "rugby"], ["🥏", "flying disc frisbee"],
      ["🎱", "8 ball pool"], ["🪀", "yo-yo"], ["🏓", "ping pong"],
      ["🏸", "badminton"], ["🏒", "ice hockey"], ["🏑", "field hockey"],
      ["🥍", "lacrosse"], ["🏏", "cricket bat"], ["🪃", "boomerang"],
      ["🥅", "goal net"], ["⛳", "golf flag"], ["🪁", "kite"],
      ["🏹", "bow arrow archery"], ["🎣", "fishing pole"], ["🤿", "diving mask"],
      ["🥊", "boxing glove"], ["🥋", "martial arts uniform"], ["🎽", "running shirt"],
      ["🛹", "skateboard"], ["🛼", "roller skate"], ["🛷", "sled"],
      ["⛸️", "ice skate"], ["🥌", "curling stone"], ["🎿", "skis"],
      ["⛷️", "skier"], ["🏂", "snowboarder"], ["🪂", "parachute"],
      ["🏋️", "weight lifter"], ["🤼", "wrestlers"], ["🤸", "cartwheel"],
      ["⛹️", "person bouncing ball"], ["🤺", "fencer"], ["🤾", "handball player"],
      ["🏌️", "golfer"], ["🏇", "horse racing"], ["🧘", "yoga meditation"],
      ["🏄", "surfer"], ["🏊", "swimmer"], ["🤽", "water polo"],
      ["🚣", "rowboat"], ["🧗", "climber"], ["🚵", "mountain biking"],
      ["🚴", "cyclist"], ["🏆", "trophy"], ["🥇", "gold medal first"],
      ["🥈", "silver medal second"], ["🥉", "bronze medal third"], ["🏅", "medal"],
      ["🎖️", "military medal"], ["🏵️", "rosette"], ["🎗️", "ribbon"],
      ["🎫", "ticket"], ["🎟️", "admission tickets"], ["🎪", "circus tent"],
      ["🤹", "juggling"], ["🎭", "performing arts masks"], ["🩰", "ballet shoes"],
      ["🎨", "art palette"], ["🎬", "clapper board movie"], ["🎤", "microphone"],
      ["🎧", "headphones"], ["🎼", "musical score"], ["🎹", "piano keyboard"],
      ["🥁", "drum"], ["🪘", "long drum"], ["🎷", "saxophone"],
      ["🎺", "trumpet"], ["🪗", "accordion"], ["🎸", "guitar"],
      ["🪕", "banjo"], ["🎻", "violin"], ["🎲", "dice game"],
      ["♟️", "chess pawn"], ["🎯", "dart target"], ["🎳", "bowling"],
      ["🎮", "video game controller"], ["🎰", "slot machine"], ["🧩", "puzzle piece"],
      ["🃏", "joker card"], ["🀄", "mahjong tile"], ["🎴", "flower cards"],
      ["🎊", "confetti ball"], ["🎉", "party popper celebrate"], ["🎈", "balloon"],
      ["🎁", "gift present"], ["🎀", "ribbon bow"], ["🪅", "pinata"],
      ["🪄", "magic wand"], ["🧸", "teddy bear"], ["🪩", "disco ball"],
    ],
    travel: [
      ["🚗", "car automobile"], ["🚕", "taxi"], ["🚙", "suv"],
      ["🚌", "bus"], ["🚎", "trolleybus"], ["🏎️", "racing car"],
      ["🚓", "police car"], ["🚑", "ambulance"], ["🚒", "fire truck"],
      ["🚐", "minibus van"], ["🛻", "pickup truck"], ["🚚", "delivery truck"],
      ["🚛", "articulated truck"], ["🚜", "tractor"], ["🏍️", "motorcycle"],
      ["🛵", "scooter"], ["🦽", "manual wheelchair"], ["🦼", "motorized wheelchair"],
      ["🛺", "auto rickshaw"], ["🚲", "bicycle bike"], ["🛴", "kick scooter"],
      ["🛹", "skateboard"], ["🚏", "bus stop"], ["🛣️", "motorway road"],
      ["🛤️", "railway track"], ["🛢️", "oil drum"], ["⛽", "fuel pump gas"],
      ["🚨", "police light"], ["🚥", "traffic light horizontal"], ["🚦", "traffic light"],
      ["🛑", "stop sign"], ["🚧", "construction sign"], ["⚓", "anchor"],
      ["🛟", "ring buoy"], ["⛵", "sailboat"], ["🛶", "canoe"],
      ["🚤", "speedboat"], ["🛳️", "passenger ship"], ["⛴️", "ferry"],
      ["🛥️", "motor boat"], ["🚢", "ship"], ["✈️", "airplane"],
      ["🛩️", "small airplane"], ["🛫", "airplane departure"], ["🛬", "airplane arrival"],
      ["🪂", "parachute"], ["💺", "seat"], ["🚁", "helicopter"],
      ["🚟", "suspension railway"], ["🚠", "cable car mountain"], ["🚡", "aerial tramway"],
      ["🛰️", "satellite"], ["🚀", "rocket"], ["🛸", "flying saucer ufo"],
      ["🛎️", "bellhop bell"], ["🧳", "luggage"], ["⌛", "hourglass"],
      ["⏳", "hourglass time"], ["⌚", "watch"], ["⏰", "alarm clock"],
      ["⏱️", "stopwatch"], ["⏲️", "timer clock"], ["🕰️", "mantelpiece clock"],
      ["🗺️", "world map"], ["🗿", "moai statue"], ["🗽", "statue of liberty"],
      ["🗼", "tokyo tower"], ["🏰", "castle"], ["🏯", "japanese castle"],
      ["🏟️", "stadium"], ["🎡", "ferris wheel"], ["🎢", "roller coaster"],
      ["🎠", "carousel horse"], ["⛲", "fountain"], ["⛱️", "beach umbrella"],
      ["🏖️", "beach"], ["🏝️", "desert island"], ["🏜️", "desert"],
      ["🌋", "volcano"], ["⛰️", "mountain"], ["🏔️", "snow capped mountain"],
      ["🗻", "mount fuji"], ["🏕️", "camping"], ["⛺", "tent"],
      ["🛖", "hut"], ["🏠", "house"], ["🏡", "house garden"],
      ["🏘️", "houses"], ["🏚️", "derelict house"], ["🏗️", "building construction"],
      ["🏭", "factory"], ["🏢", "office building"], ["🏬", "department store"],
      ["🏣", "japan post office"], ["🏤", "post office"], ["🏥", "hospital"],
      ["🏦", "bank"], ["🏨", "hotel"], ["🏪", "convenience store"],
      ["🏫", "school"], ["🏩", "love hotel"], ["💒", "wedding chapel"],
      ["🏛️", "classical building"], ["⛪", "church"], ["🕌", "mosque"],
      ["🕍", "synagogue"], ["🛕", "hindu temple"], ["🕋", "kaaba"],
      ["🌁", "foggy city"], ["🌃", "night stars city"], ["🏙️", "cityscape"],
      ["🌄", "sunrise mountains"], ["🌅", "sunrise"], ["🌆", "cityscape dusk"],
      ["🌇", "sunset buildings"], ["🌉", "bridge night"], ["♨️", "hot springs"],
      ["🎇", "sparkler fireworks"], ["🎆", "fireworks"], ["🌌", "milky way stars"],
    ],
    objects: [
      ["⌚", "watch"], ["📱", "mobile phone"], ["💻", "laptop"],
      ["⌨️", "keyboard"], ["🖥️", "desktop computer"], ["🖨️", "printer"],
      ["🖱️", "computer mouse"], ["🖲️", "trackball"], ["🕹️", "joystick"],
      ["🗜️", "clamp"], ["💽", "computer disk"], ["💾", "floppy disk save"],
      ["💿", "cd optical disk"], ["📀", "dvd"], ["📷", "camera"],
      ["📸", "camera flash"], ["📹", "video camera"], ["🎥", "movie camera"],
      ["📽️", "film projector"], ["🎞️", "film frames"], ["📞", "telephone receiver"],
      ["☎️", "telephone"], ["📟", "pager"], ["📠", "fax machine"],
      ["📺", "television"], ["📻", "radio"], ["🎙️", "studio microphone"],
      ["🎚️", "level slider"], ["🎛️", "control knobs"], ["🧭", "compass"],
      ["⏱️", "stopwatch"], ["⏲️", "timer"], ["⏰", "alarm clock"],
      ["🕰️", "mantelpiece clock"], ["⌛", "hourglass"], ["⏳", "hourglass flowing"],
      ["📡", "satellite antenna"], ["🔋", "battery"], ["🪫", "low battery"],
      ["🔌", "electric plug"], ["💡", "light bulb idea"], ["🔦", "flashlight"],
      ["🕯️", "candle"], ["🪔", "diya lamp"], ["🧯", "fire extinguisher"],
      ["🛢️", "oil drum"], ["💸", "money with wings"], ["💵", "dollar banknote"],
      ["💴", "yen banknote"], ["💶", "euro banknote"], ["💷", "pound banknote"],
      ["🪙", "coin"], ["💰", "money bag"], ["💳", "credit card"],
      ["🧾", "receipt"], ["💹", "chart increasing yen"], ["✉️", "envelope"],
      ["📧", "email"], ["📨", "incoming envelope"], ["📩", "envelope arrow"],
      ["📤", "outbox tray"], ["📥", "inbox tray"], ["📦", "package box"],
      ["📫", "mailbox"], ["📪", "closed mailbox"], ["📬", "mailbox open mail"],
      ["📭", "mailbox no mail"], ["📮", "postbox"], ["🗳️", "ballot box"],
      ["✏️", "pencil"], ["✒️", "black nib pen"], ["🖋️", "fountain pen"],
      ["🖊️", "pen"], ["🖌️", "paintbrush"], ["🖍️", "crayon"],
      ["📝", "memo notes"], ["💼", "briefcase work"], ["📁", "folder"],
      ["📂", "open folder"], ["🗂️", "card index dividers"], ["📅", "calendar"],
      ["📆", "tear off calendar"], ["🗒️", "spiral notepad"], ["🗓️", "spiral calendar"],
      ["📇", "card index"], ["📈", "chart increasing"], ["📉", "chart decreasing"],
      ["📊", "bar chart"], ["📋", "clipboard"], ["📌", "pushpin"],
      ["📍", "round pushpin location"], ["📎", "paperclip"], ["🖇️", "linked paperclips"],
      ["📏", "straight ruler"], ["📐", "triangular ruler"], ["✂️", "scissors"],
      ["🗃️", "card file box"], ["🗄️", "file cabinet"], ["🗑️", "wastebasket trash"],
      ["🔒", "locked lock"], ["🔓", "unlocked lock"], ["🔏", "lock ink pen"],
      ["🔐", "locked key"], ["🔑", "key"], ["🗝️", "old key"],
      ["🔨", "hammer"], ["🪓", "axe"], ["⛏️", "pick"],
      ["⚒️", "hammer and pick"], ["🛠️", "hammer wrench tools"], ["🗡️", "dagger"],
      ["⚔️", "crossed swords"], ["🔫", "water gun toy"], ["🪃", "boomerang"],
      ["🏹", "bow and arrow"], ["🛡️", "shield"], ["🪚", "saw"],
      ["🔧", "wrench"], ["🪛", "screwdriver"], ["🔩", "nut and bolt"],
      ["⚙️", "gear settings"], ["🗜️", "clamp"], ["⚖️", "balance scale"],
      ["🦯", "probing cane"], ["🔗", "link chain"], ["⛓️", "chains"],
      ["🪝", "hook"], ["🧰", "toolbox"], ["🧲", "magnet"],
      ["🪜", "ladder"], ["⚗️", "alembic"], ["🧪", "test tube"],
      ["🧫", "petri dish"], ["🧬", "dna"], ["🔬", "microscope"],
      ["🔭", "telescope"], ["📡", "satellite dish"], ["💊", "pill medicine"],
      ["💉", "syringe"], ["🩸", "drop blood"], ["🩹", "bandage"],
      ["🩺", "stethoscope"], ["🚪", "door"], ["🛗", "elevator"],
      ["🪞", "mirror"], ["🪟", "window"], ["🛏️", "bed"],
      ["🛋️", "couch and lamp"], ["🪑", "chair"], ["🚽", "toilet"],
      ["🪠", "plunger"], ["🚿", "shower"], ["🛁", "bathtub"],
      ["🪤", "mouse trap"], ["🪒", "razor"], ["🧴", "lotion bottle"],
      ["🧷", "safety pin"], ["🧹", "broom"], ["🪣", "bucket"],
      ["🧺", "basket"], ["🧻", "toilet paper roll"], ["🪥", "toothbrush"],
      ["🧼", "soap"], ["🫧", "bubbles"], ["🪆", "nesting dolls"],
      ["🧯", "fire extinguisher"], ["🛒", "shopping cart"], ["🎁", "gift"],
      ["🎈", "balloon"],
    ],
    symbols: [
      ["❤️", "red heart"], ["🧡", "orange heart"], ["💛", "yellow heart"],
      ["💚", "green heart"], ["💙", "blue heart"], ["💜", "purple heart"],
      ["🖤", "black heart"], ["🤍", "white heart"], ["🤎", "brown heart"],
      ["💔", "broken heart"], ["❣️", "heart exclamation"], ["💕", "two hearts"],
      ["💞", "revolving hearts"], ["💓", "beating heart"], ["💗", "growing heart"],
      ["💖", "sparkling heart"], ["💘", "cupid heart arrow"], ["💝", "heart gift"],
      ["✅", "check mark button"], ["☑️", "check box"], ["✔️", "check mark"],
      ["❌", "cross mark no"], ["❎", "cross mark button"], ["➕", "plus"],
      ["➖", "minus"], ["➗", "divide"], ["✖️", "multiply"],
      ["♾️", "infinity"], ["‼️", "double exclamation"], ["⁉️", "exclamation question"],
      ["❓", "question mark"], ["❔", "white question mark"], ["❕", "white exclamation"],
      ["❗", "exclamation mark"], ["🔴", "red circle"], ["🟠", "orange circle"],
      ["🟡", "yellow circle"], ["🟢", "green circle"], ["🔵", "blue circle"],
      ["🟣", "purple circle"], ["🟤", "brown circle"], ["⚫", "black circle"],
      ["⚪", "white circle"], ["🟥", "red square"], ["🟧", "orange square"],
      ["🟨", "yellow square"], ["🟩", "green square"], ["🟦", "blue square"],
      ["🟪", "purple square"], ["🟫", "brown square"], ["⬛", "black square"],
      ["⬜", "white square"], ["◼️", "black medium square"], ["◻️", "white medium square"],
      ["🔺", "red triangle up"], ["🔻", "red triangle down"], ["💠", "diamond dot"],
      ["🔶", "orange diamond"], ["🔷", "blue diamond"], ["🔸", "small orange diamond"],
      ["🔹", "small blue diamond"], ["🔘", "radio button"], ["🔲", "black square button"],
      ["🔳", "white square button"], ["⭐", "star"], ["🌟", "glowing star"],
      ["✨", "sparkles"], ["⚡", "lightning bolt"], ["🔥", "fire"],
      ["💯", "hundred points"], ["♻️", "recycle"], ["✳️", "asterisk"],
      ["✴️", "eight point star"], ["❇️", "sparkle"], ["🈯", "japanese reserved button"],
      ["💹", "chart increasing"], ["✅", "check mark"], ["㊙️", "secret"],
      ["㊗️", "congratulations"], ["🈴", "japanese pass"], ["🈵", "japanese full"],
      ["🈹", "japanese discount"], ["🈲", "japanese prohibited"], ["🅰️", "a button blood type"],
      ["🅱️", "b button blood type"], ["🆎", "ab button blood type"], ["🆑", "cl button"],
      ["🅾️", "o button blood type"], ["🆘", "sos"], ["❌", "cross mark"],
      ["⭕", "hollow red circle"], ["🛑", "stop sign"], ["⛔", "no entry"],
      ["📛", "name badge"], ["🚫", "prohibited"], ["💢", "anger symbol"],
      ["♨️", "hot springs"], ["🚷", "no pedestrians"], ["🚯", "no littering"],
      ["🚳", "no bicycles"], ["🚱", "non potable water"], ["🔞", "no one under 18"],
      ["📵", "no mobile phones"], ["🚭", "no smoking"], ["❗", "exclamation"],
      ["⚠️", "warning"], ["🚸", "children crossing"], ["🔱", "trident emblem"],
      ["⚜️", "fleur de lis"], ["🔰", "japanese beginner"], ["♻️", "recycling symbol"],
      ["✅", "white check mark"], ["🈶", "japanese not free"], ["🈚", "japanese free of charge"],
      ["💮", "white flower"], ["💠", "diamond with dot"], ["Ⓜ️", "circled m"],
      ["🚏", "bus stop"], ["㊙️", "japanese secret"], ["🈁", "japanese here button"],
      ["🆖", "ng button"], ["🆗", "ok button"], ["🆙", "up button"],
      ["🆒", "cool button"], ["🆕", "new button"], ["🆓", "free button"],
      ["🔟", "keycap ten"], ["🔢", "input numbers"], ["#️⃣", "keycap hash"],
      ["*️⃣", "keycap asterisk"], ["⏸️", "pause button"], ["⏹️", "stop button"],
      ["⏺️", "record button"], ["⏭️", "next track"], ["⏮️", "previous track"],
      ["⏩", "fast forward"], ["⏪", "rewind"], ["🔀", "shuffle tracks"],
      ["🔁", "repeat"], ["🔂", "repeat one"], ["▶️", "play button"],
      ["◀️", "reverse button"], ["🔼", "up button"], ["🔽", "down button"],
      ["➡️", "right arrow"], ["⬅️", "left arrow"], ["⬆️", "up arrow"],
      ["⬇️", "down arrow"], ["↗️", "up right arrow"], ["↘️", "down right arrow"],
      ["↙️", "down left arrow"], ["↖️", "up left arrow"], ["↕️", "up down arrow"],
      ["↔️", "left right arrow"], ["↪️", "right arrow curving"], ["↩️", "left arrow curving"],
      ["⤴️", "arrow curving up"], ["⤵️", "arrow curving down"], ["🔄", "counterclockwise arrows refresh"],
      ["🔃", "clockwise arrows"], ["🎦", "cinema"], ["📶", "signal strength"],
      ["🈁", "here"], ["🔣", "input symbols"], ["ℹ️", "information"],
      ["🔤", "abc input latin"], ["🔡", "abcd lowercase"], ["🔠", "abcd uppercase"],
      ["🆔", "id button"], ["🚻", "restroom"], ["🚹", "mens room"],
      ["🚺", "womens room"], ["🚼", "baby symbol"], ["⚧️", "transgender symbol"],
      ["🚾", "water closet"], ["🛂", "passport control"], ["🛃", "customs"],
      ["🛄", "baggage claim"], ["🛅", "left luggage"],
      ["㊗️", "congratulations"], ["©️", "copyright"], ["®️", "registered"],
      ["™️", "trademark"], ["🔯", "six pointed star"], ["🕎", "menorah"],
      ["☯️", "yin yang"], ["☦️", "orthodox cross"], ["🛐", "place of worship"],
      ["⛎", "ophiuchus"], ["♈", "aries"], ["♉", "taurus"],
      ["♊", "gemini"], ["♋", "cancer zodiac"], ["♌", "leo"],
      ["♍", "virgo"], ["♎", "libra"], ["♏", "scorpio"],
      ["♐", "sagittarius"], ["♑", "capricorn"], ["♒", "aquarius"],
      ["♓", "pisces"], ["🆚", "vs button"], ["💱", "currency exchange"],
      ["💲", "heavy dollar sign"], ["📴", "mobile phone off"], ["📳", "vibration mode"],
    ],
    flags: [
      ["🏳️", "white flag"], ["🏴", "black flag"], ["🏁", "checkered flag racing"],
      ["🚩", "triangular flag"], ["🏳️‍🌈", "rainbow flag pride"], ["🏳️‍⚧️", "transgender flag"],
      ["🏴‍☠️", "pirate flag"], ["🇺🇳", "united nations flag"],
      ["🇦🇫", "afghanistan af flag"],
      ["🇦🇱", "albania al flag"],
      ["🇩🇿", "algeria dz flag"],
      ["🇦🇩", "andorra ad flag"],
      ["🇦🇴", "angola ao flag"],
      ["🇦🇬", "antigua and barbuda ag flag"],
      ["🇦🇷", "argentina ar flag"],
      ["🇦🇲", "armenia am flag"],
      ["🇦🇺", "australia au flag"],
      ["🇦🇹", "austria at flag"],
      ["🇦🇿", "azerbaijan az flag"],
      ["🇧🇸", "bahamas bs flag"],
      ["🇧🇭", "bahrain bh flag"],
      ["🇧🇩", "bangladesh bd flag"],
      ["🇧🇧", "barbados bb flag"],
      ["🇧🇾", "belarus by flag"],
      ["🇧🇪", "belgium be flag"],
      ["🇧🇿", "belize bz flag"],
      ["🇧🇯", "benin bj flag"],
      ["🇧🇹", "bhutan bt flag"],
      ["🇧🇴", "bolivia bo flag"],
      ["🇧🇦", "bosnia and herzegovina ba flag"],
      ["🇧🇼", "botswana bw flag"],
      ["🇧🇷", "brazil br flag"],
      ["🇧🇳", "brunei bn flag"],
      ["🇧🇬", "bulgaria bg flag"],
      ["🇧🇫", "burkina faso bf flag"],
      ["🇧🇮", "burundi bi flag"],
      ["🇨🇻", "cabo verde cv flag"],
      ["🇰🇭", "cambodia kh flag"],
      ["🇨🇲", "cameroon cm flag"],
      ["🇨🇦", "canada ca flag"],
      ["🇨🇫", "central african republic cf flag"],
      ["🇹🇩", "chad td flag"],
      ["🇨🇱", "chile cl flag"],
      ["🇨🇳", "china cn flag"],
      ["🇨🇴", "colombia co flag"],
      ["🇰🇲", "comoros km flag"],
      ["🇨🇬", "congo cg flag"],
      ["🇨🇩", "congo drc cd flag"],
      ["🇨🇷", "costa rica cr flag"],
      ["🇨🇮", "cote d'ivoire ci flag"],
      ["🇭🇷", "croatia hr flag"],
      ["🇨🇺", "cuba cu flag"],
      ["🇨🇾", "cyprus cy flag"],
      ["🇨🇿", "czechia cz flag"],
      ["🇩🇰", "denmark dk flag"],
      ["🇩🇯", "djibouti dj flag"],
      ["🇩🇲", "dominica dm flag"],
      ["🇩🇴", "dominican republic do flag"],
      ["🇪🇨", "ecuador ec flag"],
      ["🇪🇬", "egypt eg flag"],
      ["🇸🇻", "el salvador sv flag"],
      ["🇬🇶", "equatorial guinea gq flag"],
      ["🇪🇷", "eritrea er flag"],
      ["🇪🇪", "estonia ee flag"],
      ["🇸🇿", "eswatini sz flag"],
      ["🇪🇹", "ethiopia et flag"],
      ["🇫🇯", "fiji fj flag"],
      ["🇫🇮", "finland fi flag"],
      ["🇫🇷", "france fr flag"],
      ["🇬🇦", "gabon ga flag"],
      ["🇬🇲", "gambia gm flag"],
      ["🇬🇪", "georgia ge flag"],
      ["🇩🇪", "germany de flag"],
      ["🇬🇭", "ghana gh flag"],
      ["🇬🇷", "greece gr flag"],
      ["🇬🇩", "grenada gd flag"],
      ["🇬🇹", "guatemala gt flag"],
      ["🇬🇳", "guinea gn flag"],
      ["🇬🇼", "guinea-bissau gw flag"],
      ["🇬🇾", "guyana gy flag"],
      ["🇭🇹", "haiti ht flag"],
      ["🇭🇳", "honduras hn flag"],
      ["🇭🇰", "hong kong hk flag"],
      ["🇭🇺", "hungary hu flag"],
      ["🇮🇸", "iceland is flag"],
      ["🇮🇳", "india in flag"],
      ["🇮🇩", "indonesia id flag"],
      ["🇮🇷", "iran ir flag"],
      ["🇮🇶", "iraq iq flag"],
      ["🇮🇪", "ireland ie flag"],
      ["🇮🇱", "israel il flag"],
      ["🇮🇹", "italy it flag"],
      ["🇯🇲", "jamaica jm flag"],
      ["🇯🇵", "japan jp flag"],
      ["🇯🇴", "jordan jo flag"],
      ["🇰🇿", "kazakhstan kz flag"],
      ["🇰🇪", "kenya ke flag"],
      ["🇰🇮", "kiribati ki flag"],
      ["🇰🇵", "north korea kp flag"],
      ["🇰🇷", "south korea kr flag"],
      ["🇰🇼", "kuwait kw flag"],
      ["🇰🇬", "kyrgyzstan kg flag"],
      ["🇱🇦", "laos la flag"],
      ["🇱🇻", "latvia lv flag"],
      ["🇱🇧", "lebanon lb flag"],
      ["🇱🇸", "lesotho ls flag"],
      ["🇱🇷", "liberia lr flag"],
      ["🇱🇾", "libya ly flag"],
      ["🇱🇮", "liechtenstein li flag"],
      ["🇱🇹", "lithuania lt flag"],
      ["🇱🇺", "luxembourg lu flag"],
      ["🇲🇬", "madagascar mg flag"],
      ["🇲🇼", "malawi mw flag"],
      ["🇲🇾", "malaysia my flag"],
      ["🇲🇻", "maldives mv flag"],
      ["🇲🇱", "mali ml flag"],
      ["🇲🇹", "malta mt flag"],
      ["🇲🇭", "marshall islands mh flag"],
      ["🇲🇷", "mauritania mr flag"],
      ["🇲🇺", "mauritius mu flag"],
      ["🇲🇽", "mexico mx flag"],
      ["🇫🇲", "micronesia fm flag"],
      ["🇲🇩", "moldova md flag"],
      ["🇲🇨", "monaco mc flag"],
      ["🇲🇳", "mongolia mn flag"],
      ["🇲🇪", "montenegro me flag"],
      ["🇲🇦", "morocco ma flag"],
      ["🇲🇿", "mozambique mz flag"],
      ["🇲🇲", "myanmar mm flag"],
      ["🇳🇦", "namibia na flag"],
      ["🇳🇷", "nauru nr flag"],
      ["🇳🇵", "nepal np flag"],
      ["🇳🇱", "netherlands nl flag"],
      ["🇳🇿", "new zealand nz flag"],
      ["🇳🇮", "nicaragua ni flag"],
      ["🇳🇪", "niger ne flag"],
      ["🇳🇬", "nigeria ng flag"],
      ["🇲🇰", "north macedonia mk flag"],
      ["🇳🇴", "norway no flag"],
      ["🇴🇲", "oman om flag"],
      ["🇵🇰", "pakistan pk flag"],
      ["🇵🇼", "palau pw flag"],
      ["🇵🇸", "palestine ps flag"],
      ["🇵🇦", "panama pa flag"],
      ["🇵🇬", "papua new guinea pg flag"],
      ["🇵🇾", "paraguay py flag"],
      ["🇵🇪", "peru pe flag"],
      ["🇵🇭", "philippines ph flag"],
      ["🇵🇱", "poland pl flag"],
      ["🇵🇹", "portugal pt flag"],
      ["🇶🇦", "qatar qa flag"],
      ["🇷🇴", "romania ro flag"],
      ["🇷🇺", "russia ru flag"],
      ["🇷🇼", "rwanda rw flag"],
      ["🇰🇳", "saint kitts and nevis kn flag"],
      ["🇱🇨", "saint lucia lc flag"],
      ["🇻🇨", "saint vincent and the grenadines vc flag"],
      ["🇼🇸", "samoa ws flag"],
      ["🇸🇲", "san marino sm flag"],
      ["🇸🇹", "sao tome and principe st flag"],
      ["🇸🇦", "saudi arabia sa flag"],
      ["🇸🇳", "senegal sn flag"],
      ["🇷🇸", "serbia rs flag"],
      ["🇸🇨", "seychelles sc flag"],
      ["🇸🇱", "sierra leone sl flag"],
      ["🇸🇬", "singapore sg flag"],
      ["🇸🇰", "slovakia sk flag"],
      ["🇸🇮", "slovenia si flag"],
      ["🇸🇧", "solomon islands sb flag"],
      ["🇸🇴", "somalia so flag"],
      ["🇿🇦", "south africa za flag"],
      ["🇸🇸", "south sudan ss flag"],
      ["🇪🇸", "spain es flag"],
      ["🇱🇰", "sri lanka lk flag"],
      ["🇸🇩", "sudan sd flag"],
      ["🇸🇷", "suriname sr flag"],
      ["🇸🇪", "sweden se flag"],
      ["🇨🇭", "switzerland ch flag"],
      ["🇸🇾", "syria sy flag"],
      ["🇹🇼", "taiwan tw flag"],
      ["🇹🇯", "tajikistan tj flag"],
      ["🇹🇿", "tanzania tz flag"],
      ["🇹🇭", "thailand th flag"],
      ["🇹🇱", "timor-leste tl flag"],
      ["🇹🇬", "togo tg flag"],
      ["🇹🇴", "tonga to flag"],
      ["🇹🇹", "trinidad and tobago tt flag"],
      ["🇹🇳", "tunisia tn flag"],
      ["🇹🇷", "turkey tr flag"],
      ["🇹🇲", "turkmenistan tm flag"],
      ["🇹🇻", "tuvalu tv flag"],
      ["🇺🇬", "uganda ug flag"],
      ["🇺🇦", "ukraine ua flag"],
      ["🇦🇪", "united arab emirates ae flag"],
      ["🇬🇧", "united kingdom gb flag"],
      ["🇺🇸", "united states us flag"],
      ["🇺🇾", "uruguay uy flag"],
      ["🇺🇿", "uzbekistan uz flag"],
      ["🇻🇺", "vanuatu vu flag"],
      ["🇻🇦", "vatican city va flag"],
      ["🇻🇪", "venezuela ve flag"],
      ["🇻🇳", "vietnam vn flag"],
      ["🇾🇪", "yemen ye flag"],
      ["🇿🇲", "zambia zm flag"],
      ["🇿🇼", "zimbabwe zw flag"],
      ["🇵🇷", "puerto rico pr flag"],
      ["🇬🇱", "greenland gl flag"],
      ["🇬🇮", "gibraltar gi flag"],
      ["🇲🇴", "macao mo flag"],
      ["🇧🇲", "bermuda bm flag"],
      ["🇦🇼", "aruba aw flag"],
    ],
  };
  
  // "Frequently used" gets an empty static emojis array — Form.jsx fills its
  // grid at runtime from localStorage/recent picks instead of this list.
  export const EMOJI_CATEGORIES = EMOJI_CATEGORY_META.map((c) => ({
    ...c,
    emojis: (RAW[c.key] || []).map(([char, keywords]) => ({ char, keywords })),
  }));
  
  export const DEFAULT_RECENT_EMOJIS = ["\uD83D\uDC4D", "\uD83D\uDE00", "\u2764\uFE0F", "\uD83D\uDE4F", "\uD83D\uDE02", "\uD83C\uDF89", "\uD83D\uDD25", "\u2705"];
  
  export const EMOJI_RECENTS_KEY = "agent01_recent_emojis";